# Generated by Django 4.2.7 on 2023-11-29 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0003_remove_invoice_item_invoice_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boughtitem',
            name='quantity',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
