# Generated by Django 4.2.7 on 2023-11-29 05:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0004_alter_boughtitem_quantity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoice',
            old_name='item',
            new_name='items',
        ),
    ]
