# Generated by Django 4.2.7 on 2023-11-29 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0005_rename_item_invoice_items'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='items',
            field=models.ManyToManyField(to='invoice.boughtitem'),
        ),
    ]
