# Generated by Django 4.2.7 on 2023-11-30 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0006_alter_invoice_items'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='invoice_pdf_generated',
            field=models.BooleanField(default=False),
        ),
    ]
