# Generated by Django 4.2.7 on 2023-11-30 04:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0007_invoice_invoice_pdf_generated'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoice',
            old_name='invoice_pdf_generated',
            new_name='pdf_generated',
        ),
    ]
